var car = "Mercedes";
console.log("Is car == 'Mercedes'? I predict True.");
console.log(car == 'Mercedes');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
console.log("Is car == 'Mercedes'? I predict True.");
console.log(car == 'Mercedes');
console.log("Is car == 'Audi'? I predict False.");
console.log(car == 'Audi');
console.log("Is car == 'Mercedes'? I predict True.");
console.log(car == 'Mercedes');
console.log("Is car == 'Mehran'? I predict False.");
console.log(car == 'Mehran');
console.log("Is car == 'Mercedes'? I predict True.");
console.log(car == 'Mercedes');
console.log("Is car == 'BMW'? I predict False.");
console.log(car == 'BMW');
console.log("Is car == 'Mercedes'? I predict True.");
console.log(car == 'Mercedes');
console.log("Is car == 'Chrysler'? I predict False.");
console.log(car == 'Chrysler');
